# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3.yml up`
# Add the `-d` flag at the end for detached execution
# Change "SE_NODE_GRID_URL=http://localhost:4444" to the URL/IP where the Grid is accesible.
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3.yml down`
version: "3"
services:
  chrome:
    image: selenium/standalone-chrome:4.0.0-20211025
    shm_size: 2gb
  
  bot:
    build: .
    depends_on:
      - chrome
    environment:
      - NODE_ENV=raziel
    volumes:
      - .:/usr/src/bot